### PR TITLE
Build

### PR DESCRIPTION
**Pull request by lilred**
Build system for ruby and javascript files.

Note: this might complicate a bit the merging from the `railsserver` branch.

### CODE REVIEW

**Comment by nicholasaird** [comment]
Is this to merge with master now? If so, did you show it and explain it to a few people and get their approval?

**Comment by lilred** [comment]
@nicholasaird I did not - that's the whole point of the pull request mechanism! :)

Anyone curious can hit me up.

**Comment by lilred** [comment]
@ryanordille @njfaries @nicholasaird thoughts?

**Comment by nicholasaird** [comment]
Haha, I think it's good if you show (with your laptop) to someone how it works. I see that you added files and licenses, but I don't know how to use your code. You would need to tell me and show me, otherwise I don't know what's going on.

**Comment by lilred** [comment]
That's right. Sorry, I'm a bit tired. Basically, from the top level, if you run `make`, javascript and ruby get checked, and javascript gets compiled and put in /bin. 

Further changes are possible, for example I could ditch Google Closure Compiler and go for the Uglifier.js gem to keep fewer dependencies and increase build speed. This is it for now though.

**Comment by nicholasaird** [comment]
Alright, so just show it to a few people and we can merge it.

**Comment by ryanordille** [comment]
I'll be around tomorrow after ~4 or so if you want to demo it!

**Pull request merged**
